// vue/solid/Mobile.js
import { createVNode as _createVNode, openBlock as _openBlock, createBlock as _createBlock } from "vue"

export default function render(_ctx, _cache) {
return (_openBlock(), _createBlock("svg", {
  viewBox: "0 0 20 20",
  fill: "currentColor"
}, [
  _createVNode("path", {
    "fill-rule": "evenodd",
    d: "M8 3a2 2 0 00-2 2v10a2 2 0 002 2h4a2 2 0 002-2V5a2 2 0 00-2-2H8zm2 12a1 1 0 100-2 1 1 0 000 2z",
    "clip-rule": "evenodd"
  })
]))
}

// react/solid/Mobile.jsx
import * as React from "react";

function MobileIcon(props) {
  return <svg viewBox="0 0 20 20" fill="currentColor" {...props}><path fillRule="evenodd" d="M8 3a2 2 0 00-2 2v10a2 2 0 002 2h4a2 2 0 002-2V5a2 2 0 00-2-2H8zm2 12a1 1 0 100-2 1 1 0 000 2z" clipRule="evenodd" /></svg>;
}

export default MobileIcon;
