// vue/solid/Pin.js
import { createVNode as _createVNode, openBlock as _openBlock, createBlock as _createBlock } from "vue"

export default function render(_ctx, _cache) {
return (_openBlock(), _createBlock("svg", {
  viewBox: "0 0 20 20",
  fill: "currentColor"
}, [
  _createVNode("path", {
    "fill-rule": "evenodd",
    d: "M11.21 2.543a1 1 0 01.997.25l5 5a1 1 0 01-.51 1.688l-2.204.44L12 12.414V14a1 1 0 01-.293.707l-1 1a1 1 0 01-1.414 0L7.926 14.34l-4.301 3.44a1 1 0 01-1.406-1.405l3.441-4.3-1.367-1.368a1 1 0 010-1.414l1-1A1 1 0 016 8h1.586l2.493-2.493.44-2.203a1 1 0 01.691-.761z",
    "clip-rule": "evenodd"
  })
]))
}

// react/solid/Pin.jsx
import * as React from "react";

function PinIcon(props) {
  return <svg viewBox="0 0 20 20" fill="currentColor" {...props}><path fillRule="evenodd" d="M11.21 2.543a1 1 0 01.997.25l5 5a1 1 0 01-.51 1.688l-2.204.44L12 12.414V14a1 1 0 01-.293.707l-1 1a1 1 0 01-1.414 0L7.926 14.34l-4.301 3.44a1 1 0 01-1.406-1.405l3.441-4.3-1.367-1.368a1 1 0 010-1.414l1-1A1 1 0 016 8h1.586l2.493-2.493.44-2.203a1 1 0 01.691-.761z" clipRule="evenodd" /></svg>;
}

export default PinIcon;
